### ISSUE TITLE
Download Bug

### ISSUE THREAD

**Issue by SudeepDasari** [siddk/voltron-robotics#7]
When I try to run the example code I get the following error (see below). I believe this is an issue with the google drive download, because I can successfully load the model after downloading and copying it myself. Maybe you can fix this by changing the permissions on the file?

```
>>> from voltron import instantiate_extractor, load
>>> vcond, pre = load('v-cond', device='cuda')
Downloading...
From: https://drive.google.com/uc?id=1O4oqRIblfS6PdFlZzUcYIX-Rqe6LbvnD
To: /home/sudeep/cache/v-cond/v-cond-config.json
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 2.18MB/s]
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=12g5QckQSMKqrfr4lFY3UPdy7oLw4APpG

Downloading (…)okenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28.0/28.0 [00:00<00:00, 5.70kB/s]
Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 483/483 [00:00<00:00, 119kB/s]
Downloading (…)solve/main/vocab.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 232k/232k [00:00<00:00, 4.42MB/s]
Downloading (…)/main/tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 466k/466k [00:00<00:00, 5.07MB/s]
Downloading (…)"pytorch_model.bin";: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 268M/268M [00:04<00:00, 61.9MB/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sudeep/anaconda3/envs/torch/lib/python3.8/site-packages/voltron/models/materialize.py", line 102, in load
    state_dict, _ = torch.load(checkpoint_path, map_location=device)
  File "/home/sudeep/anaconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/sudeep/anaconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sudeep/anaconda3/envs/torch/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'cache/v-cond/v-cond.pt'
```

**Comment by siddk** [comment]
Hey @SudeepDasari — thanks for flagging this. I just tried fixing the permissions, but it might just be a constraint on my drive account… will look into alternate hosting solutions if this is still a problem!

**Comment by SudeepDasari** [comment]
Hey @siddk, I'm still running into the bug, sadly! 

I've found that it's not too hard to hack around it - I just downloaded the file manually from google drive, renamed it to `v-cond.pt`, and placed it in the `~/cache/v-cond` folder. Let me know if this workaround is incorrect!

**Comment by siddk** [comment]
Hey Sudeep; that workaround is totally fine! I think what’s happening is that Google Drive is blocking downloads via gdown due to load, but going through the website is fine.

I will look into other hosting options ASAP — but let me know if this is impacting your work and we can find a faster (temporary) solution.

Thanks for giving Voltron a try!
